name: Package RPMs

on:
  push:
    tags:
      - '*'
env:
  SFOS_RELEASE: 4.5.0.16

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build armv7hl
      run:  |
        .github/workflows/build-sfos-package.sh armv7hl

    - name: Build aarch64
      run:  |
        .github/workflows/build-sfos-package.sh aarch64

    - name: Build i486
      run:  |
        .github/workflows/build-sfos-package.sh i486

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: rpms
        path: RPMS

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        artifacts: "RPMS/*.rpm"
